# git replacements for std things
alias diff='git diff --no-index'

# don't restart using cli
alias restart='echo no'

# git long commands
alias gg='git grep'
alias gcp='git cherry-pick'
alias gcpc='git cherry-pick --continue'
alias gcpa='git cherry-pick --abort'
alias gri='git rebase -i'
alias grc='git rebase --continue'
alias gra='git rebase --abort'

# git branch things
# git-update-master - fast-forward updates master branch
alias gum='git fetch origin master:master'
# git-rebase-master - rebases current branch on remote master
alias grm='git rebase master'
# git-update-rebase-master - update and rebase master
alias gurm='gum && grm'

rg() {
  if [ -t 1 ] ; then
    command rg -p "$@" | less -RFX
  else
    command rg "$@"
  fi
}
