set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
" Keep Plugin commands between vundle#begin/end.
call vundle#begin()
" let Vundle manage Vundle, required
" plugins from GitHub repos
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-sensible'
Plugin 'tpope/vim-fugitive'
Plugin 'vim-scripts/click.vim'
Plugin 'kergoth/vim-bitbake'

call vundle#end()            " required
filetype plugin indent on    " required
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ


" non-plugin stuff
set title
set smartcase

" tabstop should ALWAYS be 8
" shiftwidth and softtabstop should be same
set expandtab
set shiftwidth=2
set softtabstop=2

" since my background is dark
" I need to manually change the highlight color
"hi Visual ctermbg=black
set cursorline
set background=light
hi Visual cterm=NONE ctermbg=Black
hi CursorLine cterm=NONE ctermbg=Black

" turn of EX mode, it's actually the worst
map Q <Nop>

" filetype overrides
augroup filetypedetect
    au BufRead,BufNewFile Makefile.inc set filetype=make
augroup END

augroup filetypedetect
    au BufRead,BufNewFile *.click *.template set filetype=click
augroup END
